spring.application.name=smart-inventory

server.port=8081

# PostgreSQL
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/smart_inventory
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Ollama
spring.ai.ollama.base-url=http://host.docker.internal:11434
spring.ai.ollama.chat.options.model=llama3.2